name: neo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - ipython
  - numpy<2.0.0
  - pandas
  - pytorch
  - transformers
  - scipy
  - scikit-learn
  - appdirs
  - huggingface_hub<0.23.0
  - accelerate=0.31.0
  - wandb
  - pynvml