name: neo_3
channels:
  - conda-forge
  - defaults
  - nvidia
dependencies:
  - python=3.9
  - ipython
  - numpy<2.0.0
  - pandas
  - scipy
  - scikit-learn
  - appdirs
  - huggingface_hub<0.23.0
  - wandb
  - pynvml
  - rich
  - matplotlib
  - requests
  - tqdm
  - pip
  - importlib-metadata
  - pip:
    - aiohttp
    - accelerate
    - sentence-transformers
    - transformers